### ISSUE TITLE
Bad bojler...

### ISSUE THREAD

**Issue by OrionPro** [Slicejack/bojler#109]
What did you do with the project? Previously, everything was fine, there was a dev option in gulp. There were inline styles right in html. Where is the server http://localhost:8000? Now there is nothing at all, and it's not clear how to work with this. Now either use the old version of 2017, or just go to something else .... sorry for the bad english.

**Comment by alenvuletic** [comment]
Hi @OrionPro!

We've updated Bojler and now it is pure CSS framework for emails. You can find inliner and other tools in this repo - https://github.com/Slicejack/bojler-skeleton

I hope you'll try this new concept and give us more feedback about it.

Thanks for your input!

**Comment by alenvuletic** [comment]
Hi @OrionPro, we updated bojler to v4.0.0, now everything will function as it has before.

Thanks,
Alen :)

**Comment by OrionPro** [comment]
@alenvuletic  It is very good! Because I'm using your old project ...)

**Comment by alenvuletic** [comment]
Thanks @OrionPro, we have updated our documentation site also - https://bojler.slicejack.com

**Comment by OrionPro** [comment]
@alenvuletic I have already checked something in a new project, now everything works as it should! Thank you! Class column (column-6 ect..) works as expected, in the old version not work this classes...

**Comment by alenvuletic** [comment]
@OrionPro Awesome! If there's something we can improve or if you find bug please create issue and we can discuss / resolve it 👍
