### ISSUE TITLE
Gmail isnt responsive due to escaped @

### ISSUE THREAD

**Issue by Bizarro181** [Slicejack/bojler#115]
I believe in an attempt to sanitize CSS, gmail is stripping the style block that contains all the media queries due to not liking the `/@sm` classes.  I was getting no responsive styles in the gmail app and web client until I renamed these classes to `-sm`

**Comment by alenvuletic** [comment]
Hi @Bizarro181, thanks for reporting this!

I've created new PR (#117), we'll merge it to master and release it for v4.1.0.

Old `@` markup will be available till v5 to make everything backward compatible.

We replaced `@` with `:`.

**Comment by alenvuletic** [comment]
@Bizarro181, we just released v4.1.0 with this issue fixed. — https://github.com/Slicejack/bojler/releases/tag/v4.1.0

Thanks once again!
