### ISSUE TITLE
[feature request] pug templates

### ISSUE THREAD

**Issue by alechance** [Slicejack/bojler#129]
Hello,

I've been testing your project and trying to add pug templates on top of your gulp tasks, with no success.
Based on the @akzhan/gulp-juice documentation, here's what I should do

```js
var juice = require('gulp-juice'),
  jade = require('gulp-jade');
 
gulp.task('bootloader', function(){
  gulp.src('./app/templates/bootloader.jade')
    .pipe(jade({pretty: true}))
    .pipe(gulp.dest('./.build'))
    .pipe(juice())
    .pipe(gulp.dest('./.build'));
});
```

Can you help me?
Thank you for your time!

**Comment by alenvuletic** [comment]
Hi @alechance, unfortunately we're not thinking about adding PUG templates currently.

Thanks!
