### ISSUE TITLE
Bulletproof Custom Fonts with @font-face

### ISSUE THREAD

**Issue by jkupczak** [Slicejack/bojler#13]
Would be great to see a block of commented code that explains the most bulletproof way to use custom fonts with @font-face. For example, some considerations have to be made for Outlook: https://litmus.com/community/discussions/36-outlook-and-fallback-fonts#comment-2459

**Comment by alenvuletic** [comment]
Hi @jkupczak,

We have implemented `system fonts stack` (#8) few days ago and we'll rely on them as typography foundations for this boilerplate.

Custom fonts usage depends on developers and it's up to them how to implement it. Our mission/goal is to give starting point for developers and we have to stick to that.

Thanks :)
