### ISSUE TITLE
Gmail isn't responsive

### ISSUE THREAD

**Issue by laurensf** [Slicejack/bojler#130]
The template in Gmail isn't responsive. If I remove every styling which contains \:sm and \@sm it seems to work again.

**Comment by dcpedit** [comment]
It looks like gmail is also ignoring classnames with the ":" character now.  Modifying _utilities.scss to use class names like px-1-sm seems to work ok.

**Comment by alenvuletic** [comment]
Hi @laurensf, you're talking about web-browser version of Gmail or an smartphone application?

Thanks for your report!

**Comment by dcpedit** [comment]
@alenvuletic , I was able to see this issue as well.  I'm using the Gmail app for Android.

**Comment by laurensf** [comment]
Hi @alenvuletic. I had this problem with the IOS Gmail app and also with the mobile web-browser version of Gmail

**Comment by alenvuletic** [comment]
Hi @laurensf and @dcpedit, I've added new responsive utility classes for you with "-" character (https://github.com/Slicejack/bojler/commit/bf5aaf07a52a8dacabffeef26b198eb5f7ee151f). Updates are released with v4.1.4.

Thanks for your contribution!
