### ISSUE TITLE
Gmail responsive issue?

### ISSUE THREAD

**Issue by graphicmist** [Slicejack/bojler#135]
Hi,

First of all, thanks for the awesome boilerplate. I loved developing mailer on bojler and it was super fast.
I tested my emailer on Gmail app client and looks like the email is not responsive at all. Looking into past issues, looks like this was fixed. 
Can someone verify?

**Comment by alenvuletic** [comment]
Hi @graphicmist, can you try to remove all the classes with `@` and `:` characters and leave ones with `-`?

Example:

`.table\:sm,
.table\@sm,
.table-sm {}`

should become

`.table-sm {}`

Let me know if this helps, thanks!

**Comment by graphicmist** [comment]
I think it was some problem with the email testing platform which i used. With Mailchimp, it is working fine.
