### ISSUE TITLE
bojler buttons aren't clickable across the button

### ISSUE THREAD

**Issue by rogerpence** [Slicejack/bojler#139]
The only part of a button that is clickable is the text. This is especially noticeable on full-width buttons. 

This might let a sloppy user miss a click which means a potential missed opportunity.  A klunky work-around is to add a bunch of &nbsp;'s around the text. 

Otherwise, I am very impressed with the work you've done. You struck a great balance between abstraction and writing bare-metal HTML for emails. Thank you very much.

**Comment by alenvuletic** [comment]
Hi @rogerpence, I'll leave this issue open and I'll consider your request for next release.

Buttons are created that way to support Outlook email clients but I think we can figure something out to make it more accessible.

Thanks for your request! :)

**Comment by rogerpence** [comment]
Alen--

Than you for your reply. I have used a ton of email framework competitors
(Foundation-vendor apparently lost interest and it's too complex;
maizzle-just doesn't work-maybe too immature; mjml-I have gotten results
with this one but its just a little complex); none them are as well-done as
Bojler. You've done a great job with it.



rp

**Comment by alenvuletic** [comment]
Hi @rogerpence, this will be released in `v5` soon.

Thanks!
