### ISSUE TITLE
Premade templates

### ISSUE THREAD

**Issue by alenvuletic** [Slicejack/bojler#14]
It would be great to have few premade templates with components as an example for users.

**Features:**
- MailChimp support (MailChimp snippets implemented)

**Comment by nirajrajgor** [comment]
I am very much interested in coding the premade templates, but i don't know from where to start. Is there any guide on developing templates defining the desired folder structure or code specification for template.

**Comment by alenvuletic** [comment]
Hi everyone!

We'll soon start working on few email templates for Bojler.

We're thinking about:
- Basic _(Simple template with header, footer, content and CTA button)_
- Basic template variations _(Such as success, danger and warning variations)_
- Password reset template

@nirajrajgor Later we will add template contribution guide to our documenation and everyone will be able to contribute and create open-source Bojler templates!

**Comment by nirajrajgor** [comment]
@alenvuletic cool !!
Hope this gets started asap, excited to work on templates.

**Comment by alenvuletic** [comment]
We'll add templates in v3.2.0 — https://github.com/Slicejack/bojler/milestone/11

Closing ...
