### ISSUE TITLE
unable to disable eslint rules (Tabs)

### ISSUE THREAD

**Issue by JoueBien** [Slicejack/bojler#140]
Please don't inforce tabs - not everyone uses tabs. Internally the place where I work we use 2 spaces. 
In general please let people disable rules - half of them are just plain annoying when you have to solve 15 warnings that in any other framework by default would be ok.

**Comment by alenvuletic** [comment]
Hi @JoueBien, there are `.stylelintrc` and `.eslintrc`, adjust them according to your needs.

Thanks,
Alen :)
