### ISSUE TITLE
Partials

### ISSUE THREAD

**Issue by Matzu89** [Slicejack/bojler#142]
Hi guys,

First of all, `Bojler` succesfully removed my troubles with email clients. Thank you for that!

Now wondering, is it possible to include partials, for instance to always include the same header or footer?

If so, how? 
If not, can we make it so?

Please share your thoughts

**Comment by alenvuletic-convertiv** [comment]
Hi @Matzu89, unfortunately Bojler don't have support for partials.

To make it possible you would have to use some kind of templating language.

If you can, create a PR and we will review it and hopefully merge it into master :)

Thanks!

**Comment by alenvuletic** [comment]
Hi @Matzu89, unfortunately Bojler don't have support for partials.

To make it possible you would have to use some kind of templating language.

If you can, create a PR and we will review it and hopefully merge it into master :)

Thanks!

**Comment by luigimannoni** [comment]
@Matzu89 probably my reply comes in very late but I did in fact written already what you ask last year for developing quick emails to a client, you can find it here: https://github.com/luigimannoni/pug-bojlerplate

It is a fork of Bojler 4.1.1 with the addition of Pug, you can write your own mixins or just use the ones I've put there (you might need a bit of customisation probably) you can use it if you still need it.
