### ISSUE TITLE
Gmail Hero component issue

### ISSUE THREAD

**Issue by ghost** [Slicejack/bojler#17]
Hi!
Thanks for this boilerplate! I found issue with Hero component in Gmail on PC web browser.
Aligment is broken - no center, always push on left.
https://ibb.co/dCnv3Q Here is preview.

And also button Click me! lost its style... Any ideas? This is pure template from Docs, and send via AcyMailing Joomla component as HTML message. The same email send to Thunderbird looks flawless!

**Comment by PrestaShark** [comment]
Hah. and also button Click me! lost its style... Any ideas? This is pure template from Docs.

**Comment by alenvuletic** [comment]
Hi @PrestaShark, please can you upload your `.html` file somewhere, maybe jsfiddle or codepen?

**Comment by ghost** [comment]
Sure! https://jsfiddle.net/3r1j0s7L/
Here it is. Thanks for support!

**Comment by alenvuletic** [comment]
@PrestaShark, as I can see you're missing this part on the beginning of your `.html` file:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
	<head>
```
