### ISSUE TITLE
youtube video lesson

### ISSUE THREAD

**Issue by zalexstudios** [Slicejack/bojler#181]
Hey!
Could you create an instructional video of the layout on YouTube!
Where they showed how to set up and run a project!
Make up completely from scratch.

Thank you for you work!

**Comment by alenvuletic** [comment]
Hi @zalexstudios, full project documentation can be found at https://bojler.slicejack.com/.

We are not planning to create youtube videos, we think documentation is enough to get projects up and running quickly.

Thanks for the suggestion!
