### ISSUE TITLE
Hide Gmail download icon no longer works

### ISSUE THREAD

**Issue by jkupczak** [Slicejack/bojler#2]
Looks like this happened when Google updated Gmail in Sep/Oct. They added support for classes and id's but removed attribute selector support. As a result this code no longer works.

	* img[tabindex="0"] + div{
		/* Hide download icon in Gmail */
		display: none !important;
	}

Instead, using `img + div > div` works. But obviously that can be dangerous since it's so general so adding a warning would be a good idea (or maybe not even include it at all?). Alternatively you can link the image with `<a>` or add a class to target it better.

**Comment by alenvuletic** [comment]
Hi @jkupczak,

Thanks for update!

Unfortunately that snippet is outdated.
You can try methods listed in [this blog post](https://www.emailonacid.com/blog/article/email-development/prevent-gmail-from-displaying-image-download-button-in-email/).

Thanks,
Alen :)
