### ISSUE TITLE
How do you copy images over?

### ISSUE THREAD

**Issue by pathetix** [Slicejack/bojler#21]
Just read up about gulp and not sure how to copy my images to the public folder.
I read that you can compress them as well but it is quite a challenge for me.

I know I'm supposed to use a fixed URL for images but I need to develop locally.

**Comment by alenvuletic** [comment]
Hi @pathetix, unfortunately this is not implemented yet.
We'll implement images compress and copy feature as soon as possible.

Thanks for commenting!

**Comment by alenvuletic** [comment]
Hi @pathetix, this is solved in v2.1.0.
Please read [updated documentation](http://bojler.slicejack.com/getting-started/#compress-and-optimize-your-images).

Also, we're not going to implement automated images compress anytime soon.

Thanks! :)
