### ISSUE TITLE
Android 4.4 Kit-Kat email centering no longer supported with attribute selector

### ISSUE THREAD

**Issue by jkupczak** [Slicejack/bojler#3]
Much like the other issue I posted, I believe this is another victim of the Gmail update last fall. Attribute selectors are no longer supported so I imagine this no longer works.

```
			div[style*="margin: 16px 0"]{
				/* Centering emails in Android 4.4 KitKat. More info: - https://blog.jmwhite.co.uk/2015/09/19/revealing-why-emails-appear-off-centre-in-android-4-4-kitkat */
				margin: 0 !important;
			}
```

Alternatively, this might be a good solution?

```

		body > div {
			margin:0 !important;
		}
```

**Comment by alenvuletic** [comment]
@jkupczak - Unfortunately Android 4.4 is currently unavailable on Litmus and I can't test this issue.

![1](https://cloud.githubusercontent.com/assets/8091352/22589201/5d9cf03e-ea09-11e6-8b31-6330c1884c53.png)

**Comment by alenvuletic** [comment]
@jkupczak I've removed this one from templates. Our table goes full width on mobile devices so this one is not necessary.

Thanks!
