### ISSUE TITLE
Preheader

### ISSUE THREAD

**Issue by alenvuletic** [Slicejack/bojler#5]
It would be great to have preheader example in every `.html` file.

**Comment by rcotrina94** [comment]
By the way: It should be "[**preview text**](https://www.litmus.com/blog/the-ultimate-guide-to-preview-text-support#:~:text=Preview%20text%20vs,it%E2%80%99s%20called%20preheader)", as per the article mentioned in [the implementation](https://github.com/Slicejack/bojler/commit/d9c0d2830d9b91064cda785085581fd5f8f12793#diff-5a77fcb9885a9d3eb483eb4d0fd4237eecfaa5dbcc88a329cd756f2d7bd2d02aR252-R253). Should I open a new Issue? 🤔 

/> Cheers from Perú!

**Comment by alenvuletic** [comment]
Hi @rcotrina94, you can open a new issue for it but only if you're going to create a PR for it. Otherwise there's no need for it.

Thanks,
Alen :)
