### ISSUE TITLE
npm run gulp : No file output

### ISSUE THREAD

**Issue by franck-rmp** [Slicejack/bojler#53]
`npm run gulp` doesn't produce any output in the `/public` directory

```
// Default (Build)
gulp.task(
	'default',
	gulp.series( [
		'build:sass',
		'inline:css',
		'clean:css',
		'clean:html',
	] )
);
```
**STEP 1**
`npm run gulp build:sass` 
Works properly and generate a `/public/css` directory with the two CSS files

**STEP 2**
`npm run gulp inline:css` 
Doesn't generate anything since it's looking for `/public/*.html` files not generated yet

**Comment by alenvuletic** [comment]
Hi @franck-rmp, thanks for your bug report!
This should be fixed in new release (v2.1.2).
