### ISSUE TITLE
Buttons: only text clickable

### ISSUE THREAD

**Issue by rubenstolk** [Slicejack/bojler#55]
I think it would be good to have the `<a>` cover the full button so that the full button is clickable.

**Comment by alenvuletic** [comment]
@rubenstolk: Target area is small because we had to apply padding to table-cell instead of the `<a>`. That's because some Outlook e-mail clients do not support paddings on `<a>` element.

**Comment by rubenstolk** [comment]
Hmm that's the reason. I see that almost all mails that I receive do the padding on the button so not sure if we should follow Outlook here...

**Comment by alenvuletic** [comment]
Our goal is to support as much email clients as we can, in this case we'll leave this as it is.
Once we decide to drop support for Outlook we'll update buttons too.

Thanks @rubenstolk !
