### ISSUE TITLE
Working on multiple templates in the same `source` folder

### ISSUE THREAD

**Issue by metamas** [Slicejack/bojler#56]
Can I work on multiple templates in the `source` folder? If so, how is it recommended to keep their dependencies separate? I would like to have a separate `inlined.scss` and `embedded.scss` for each template — say a `/source/newsletter.html` and a `/source/announcement.html`.

**Comment by alenvuletic** [comment]
Hi @metamas

You can create multiple templates (`.html` files) but you can't create separate `inlined.scss` and `embedded.scss` for each `.html` file.

Bojler compiler will not add unused CSS to your `.html` files so there's no need for separate `.scss` files. If you have different email theme just create new project with Bojler.
