### ISSUE TITLE
Using Klaviyo tags

### ISSUE THREAD

**Issue by vagrantrobbie** [Slicejack/bojler#59]
Klaviyo https://www.klaviyo.com tags such as {{ first_name }} get converted to juice block code, eg JUICE_CODE_BLOCK_33_

Can we escape the preprocess of these tags some how?

**Comment by alenvuletic** [comment]
We don't have that option right now, I'll keep you posted about this issue.
Thanks! :)

**Comment by alenvuletic** [comment]
Moved to: https://github.com/Slicejack/bojler-skeleton/issues/1
